### ISSUE TITLE
avoid unused method receiver

### ISSUE THREAD

**Issue by lerichardson** [zpratt/jig#14]
I noticed there is an [unused method here](https://github.com/zpratt/jig/blob/main/adapters/windows.go#L32-L32) that I could send a PR for Hacktoberfest to fix if needed  
  
**full disclosure** I found this on [deepsource.io](https://deepsource.io) so I'm not sure if this actually is used.

Levi

**Comment by jones2026** [comment]
I think we need to start implementation of that method, instead of removing it could you add the code to accomplish that task?

**Comment by jones2026** [comment]
#18 closes this issue
